# Hi
## Hi
### Hi
#### Hi
##### Hi
###### Hi

In [3]:
import numpy as np

In [5]:
l1=np.array([x for x in range(10)])
print(l1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(type(l1))
print(l1.shape)
print(l1*2)

<class 'numpy.ndarray'>
(10,)
[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
l2=[x for x in range(10)]
print(l2*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [23]:
print(l1.ndim)

1


In [19]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
print(list2d.ndim)
print(list2d.shape)

2
(4, 5)


In [25]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [28]:
print(list3d.size)
print(list3d.shape)
print(list3d.ndim)

60
(3, 4, 5)
3


# Reshaping

### 1d

In [35]:
list1d=[x for x in range(0,3*4)]
list1d=np.array(list1d)
list2d=list1d.reshape(3,4)
list3d=list1d.reshape(3,2,2)

In [39]:
print(list2d)
print('*'*100)
print(list3d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


### 2d

In [40]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
r,c=list2d.shape
print(r,c)


4 5


In [45]:

list1d=list2d.reshape(r*c)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
list3d=list2d.reshape(2,r//2,c)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 3d

In [50]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [51]:
z,r,c=list3d.shape
print(z,r,c)

3 4 5


In [52]:
list2d=list3d.reshape(r*z,c)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
list2d=list3d.reshape(r,c*z)
list2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [54]:
list1d=list3d.reshape(r*c*z)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
list1d=list3d.reshape(-1)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])