# Hi
## Hi
### Hi
#### Hi
##### Hi
###### Hi

In [3]:
import numpy as np

In [5]:
l1=np.array([x for x in range(10)])
print(l1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(type(l1))
print(l1.shape)
print(l1*2)

<class 'numpy.ndarray'>
(10,)
[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
l2=[x for x in range(10)]
print(l2*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [23]:
print(l1.ndim)

1


In [19]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
print(list2d.ndim)
print(list2d.shape)

2
(4, 5)


In [25]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [28]:
print(list3d.size)
print(list3d.shape)
print(list3d.ndim)

60
(3, 4, 5)
3


# Reshaping

### 1d

In [35]:
list1d=[x for x in range(0,3*4)]
list1d=np.array(list1d)
list2d=list1d.reshape(3,4)
list3d=list1d.reshape(3,2,2)

In [39]:
print(list2d)
print('*'*100)
print(list3d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


### 2d

In [40]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
r,c=list2d.shape
print(r,c)


4 5


In [45]:

list1d=list2d.reshape(r*c)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
list3d=list2d.reshape(2,r//2,c)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 3d

In [50]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [51]:
z,r,c=list3d.shape
print(z,r,c)

3 4 5


In [52]:
list2d=list3d.reshape(r*z,c)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
list2d=list3d.reshape(r,c*z)
list2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [54]:
list1d=list3d.reshape(r*c*z)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
list1d=list3d.reshape(-1)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
print(list1d.dtype)
print(list2d.dtype)
print(list3d.dtype)


int64
int64
int64


# Array Creation Methods


In [ ]:
list1d=[x for x in range(0,3*4)]                #list
arr=np.array(list1d)
print(arr)
list1d=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)   #tuple
arr=np.array(list1d)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# np.zeros

In [66]:
arr=np.zeros(5)
print(arr)
print("*"*100)
arr=np.zeros((3,5))
print(arr)
print("*"*100)
arr=np.zeros((3,2,5))
print(arr)

[0. 0. 0. 0. 0.]
****************************************************************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
****************************************************************************************************
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


# np.ones

In [69]:
arr=np.ones(5)
print(arr)
print("*"*100)
arr=np.ones((3,5))
print(arr)
print("*"*100)
arr=np.ones((3,2,5))
print(arr)

[1. 1. 1. 1. 1.]
****************************************************************************************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
****************************************************************************************************
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## arange

In [72]:
print(np.arange(100))
print('*'*100)
print(np.arange(10,100,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
****************************************************************************************************
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


# linspace

In [76]:
print(np.linspace(10,100,20))
print('*'*100)


[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]
****************************************************************************************************


# eye

In [79]:
print(np.eye(3))
print('*'*100)
print(np.eye(4,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
****************************************************************************************************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# fill

In [82]:
print(np.full(3,8))
print('*'*100)
print(np.full((2,3,4),7))

[8 8 8]
****************************************************************************************************
[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


# random.randint

In [92]:
print(np.random.randint(3))
print('*'*100)
print(np.random.randint(3,100))
print('*'*100)
print(np.random.randint(100,200,10))
print('*'*100)
print(np.random.randint(100,200,(3,5)))
print('*'*100)
print(np.random.randint(100,200,(3,5,4)))


2
****************************************************************************************************
92
****************************************************************************************************
[136 137 188 114 168 193 114 156 187 138]
****************************************************************************************************
[[164 119 156 126 181]
 [160 174 158 155 120]
 [112 131 198 116 141]]
****************************************************************************************************
[[[199 126 105 188]
  [155 101 184 100]
  [117 156 119 158]
  [180 162 149 136]
  [119 106 164 100]]

 [[124 144 176 179]
  [127 158 170 109]
  [136 107 118 142]
  [166 171 182 187]
  [135 102 187 152]]

 [[113 170 138 197]
  [118 142 136 122]
  [185 177 103 157]
  [163 105 151 168]
  [101 157 104 120]]]


# random.random

In [95]:
print(np.random.random(3))
print('*'*100)
print(np.random.random((3,5)))
print('*'*100)
print(np.random.random((3,5,4)))


[0.43140522 0.8931038  0.53511925]
****************************************************************************************************
[[0.19610157 0.48338626 0.72082287 0.44527807 0.51918601]
 [0.14062455 0.72380391 0.20465235 0.90921869 0.75430691]
 [0.37122636 0.43862124 0.43095722 0.48300723 0.86759546]]
****************************************************************************************************
[[[0.34756823 0.72533536 0.88675791 0.62712101]
  [0.27834559 0.3454017  0.23502977 0.52395846]
  [0.18492287 0.63825372 0.31812036 0.89855132]
  [0.95179785 0.97812005 0.84337834 0.0707898 ]
  [0.70569448 0.30412981 0.32066905 0.31485345]]

 [[0.53078125 0.05797049 0.53261691 0.25487343]
  [0.35809117 0.86205662 0.95881607 0.88698019]
  [0.87621901 0.64120099 0.92494812 0.02583286]
  [0.42585221 0.22165852 0.12528745 0.44329281]
  [0.34891956 0.6882133  0.83973054 0.48197138]]

 [[0.6002394  0.05651132 0.2109876  0.83321742]
  [0.58524771 0.70031089 0.93017466 0.36382114]
  [0.136

# Indexing

## 1D array indexing

In [100]:
arr=np.arange(10,101,10)
print(arr)
print(arr[2])
print(arr[-1])

[ 10  20  30  40  50  60  70  80  90 100]
30
100


## 2D array indexing

In [104]:
arr=np.random.randint(1,100,(4,5))
print(arr)
print(arr[1,1])
print(arr[1][1])

[[70 99 56 20 98]
 [23 18 62 96 97]
 [93  6 13 43 73]
 [26 50 59  7 80]]
18
18


## 3D array indexing

In [116]:
arr=np.random.randint(1,100,(3,2,4))
print(arr)
print('*'*100)
print(arr[0,1,3])
print('*'*100)
print(arr[0][1][3])

[[[49 63  4 78]
  [32 97 68  5]]

 [[58 39 92 54]
  [13 42 17 75]]

 [[17 39 16 47]
  [57 63 18 10]]]
****************************************************************************************************
5
****************************************************************************************************
5


# slicing

## 1d slicing

In [117]:
arr_1d=np.random.randint(1,100,10)
print(arr_1d)
print('*'*100)
print(arr_1d[2:5])
print('*'*100)
print(arr_1d[2:8:2])
print('*'*100)
print(arr_1d[2:])
print('*'*100)
print(arr_1d[:5])
print('*'*100)
print(arr_1d[::2])

[76 68 70 50  6 17 10 76 99 53]
****************************************************************************************************
[70 50  6]
****************************************************************************************************
[70  6 10]
****************************************************************************************************
[70 50  6 17 10 76 99 53]
****************************************************************************************************
[76 68 70 50  6]
****************************************************************************************************
[76 70  6 10 99]


## 2d slicing

In [118]:
arr_2d=np.random.randint(1,100,(4,6))
print(arr_2d)
print('*'*100)
print(arr_2d[1,2:4])
print('*'*100)
print(arr_2d[2:4,1:3])

[[49 59 28 77 68  2]
 [52 14 45 86 98  3]
 [ 6 32 51 37 28 91]
 [71 90 74 58 56 82]]
****************************************************************************************************
[45 86]
****************************************************************************************************
[[32 51]
 [90 74]]


## 3d slicing

In [123]:
arr_3d=np.random.randint(1,100,(4,4,5))
print(arr_3d)
print('*'*100)
print(arr_3d[2,0,1:])
print('*'*100)
print(arr_3d[1:3,1:3,1:3])

[[[40 25 17 91 74]
  [36 10 37 51 72]
  [90 82 65 53 53]
  [80 62 48 12 54]]

 [[95 61 34 44 15]
  [95 72 39 25 91]
  [78 86 50 91 96]
  [34 85 41 78 75]]

 [[59 74 98 68 75]
  [52 38 92 83 40]
  [38 59 52 43 69]
  [ 7 82 48  3 81]]

 [[18  8 48 79 35]
  [88 58 22 24  3]
  [99 91 46 99 86]
  [39  1 18 13 90]]]
****************************************************************************************************
[74 98 68 75]
****************************************************************************************************
[[[72 39]
  [86 50]]

 [[38 92]
  [59 52]]]
