# Hi
## Hi
### Hi
#### Hi
##### Hi
###### Hi

In [2]:
import numpy as np

In [3]:
l1=np.array([x for x in range(10)])
print(l1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(type(l1))
print(l1.shape)
print(l1*2)

<class 'numpy.ndarray'>
(10,)
[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
l2=[x for x in range(10)]
print(l2*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
print(l1.ndim)

1


In [7]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
print(list2d.ndim)
print(list2d.shape)

2
(4, 5)


In [9]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [10]:
print(list3d.size)
print(list3d.shape)
print(list3d.ndim)

60
(3, 4, 5)
3


# Reshaping

### 1d

In [11]:
list1d=[x for x in range(0,3*4)]
list1d=np.array(list1d)
list2d=list1d.reshape(3,4)
list3d=list1d.reshape(3,2,2)

In [12]:
print(list2d)
print('*'*100)
print(list3d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************************************************************************************************
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


### 2d

In [13]:
list2d=[[x+j for j in range(5)] for x in range(0,5*4,5)]
list2d=np.array(list2d)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
r,c=list2d.shape
print(r,c)


4 5


In [15]:

list1d=list2d.reshape(r*c)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
list3d=list2d.reshape(2,r//2,c)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 3d

In [17]:
list3d=[[[x+j for j in range(5)] for x in range(0,5*4,5)] for z in range(3)]
list3d=np.array(list3d)
list3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [18]:
z,r,c=list3d.shape
print(z,r,c)

3 4 5


In [19]:
list2d=list3d.reshape(r*z,c)
list2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
list2d=list3d.reshape(r,c*z)
list2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
list1d=list3d.reshape(r*c*z)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
list1d=list3d.reshape(-1)
list1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
print(list1d.dtype)
print(list2d.dtype)
print(list3d.dtype)


int64
int64
int64


# Array Creation Methods


In [24]:
list1d=[x for x in range(0,3*4)]                #list
arr=np.array(list1d)
print(arr)
list1d=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)   #tuple
arr=np.array(list1d)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# np.zeros

In [25]:
arr=np.zeros(5)
print(arr)
print("*"*100)
arr=np.zeros((3,5))
print(arr)
print("*"*100)
arr=np.zeros((3,2,5))
print(arr)

[0. 0. 0. 0. 0.]
****************************************************************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
****************************************************************************************************
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


# np.ones

In [26]:
arr=np.ones(5)
print(arr)
print("*"*100)
arr=np.ones((3,5))
print(arr)
print("*"*100)
arr=np.ones((3,2,5))
print(arr)

[1. 1. 1. 1. 1.]
****************************************************************************************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
****************************************************************************************************
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## arange

In [27]:
print(np.arange(100))
print('*'*100)
print(np.arange(10,100,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
****************************************************************************************************
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


# linspace

In [28]:
print(np.linspace(10,100,20))
print('*'*100)


[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]
****************************************************************************************************


# eye

In [29]:
print(np.eye(3))
print('*'*100)
print(np.eye(4,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
****************************************************************************************************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# fill

In [30]:
print(np.full(3,8))
print('*'*100)
print(np.full((2,3,4),7))

[8 8 8]
****************************************************************************************************
[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


# random.randint

In [31]:
print(np.random.randint(3))
print('*'*100)
print(np.random.randint(3,100))
print('*'*100)
print(np.random.randint(100,200,10))
print('*'*100)
print(np.random.randint(100,200,(3,5)))
print('*'*100)
print(np.random.randint(100,200,(3,5,4)))


2
****************************************************************************************************
23
****************************************************************************************************
[178 151 120 123 177 162 107 119 156 116]
****************************************************************************************************
[[135 169 169 124 179]
 [163 118 146 199 161]
 [156 187 106 193 151]]
****************************************************************************************************
[[[167 163 147 143]
  [160 131 170 127]
  [186 155 155 185]
  [183 161 169 123]
  [150 183 181 142]]

 [[167 138 137 101]
  [118 105 103 141]
  [131 125 176 180]
  [173 116 104 131]
  [172 161 165 164]]

 [[133 145 122 125]
  [165 168 197 130]
  [182 123 186 163]
  [124 156 168 183]
  [138 133 129 131]]]


# random.random

In [32]:
print(np.random.random(3))
print('*'*100)
print(np.random.random((3,5)))
print('*'*100)
print(np.random.random((3,5,4)))


[0.14934218 0.66598316 0.15749369]
****************************************************************************************************
[[0.59883149 0.9698542  0.12270926 0.81656679 0.73033294]
 [0.66971421 0.46068355 0.34764404 0.340671   0.65153842]
 [0.59678093 0.0986345  0.96109765 0.04949431 0.87687406]]
****************************************************************************************************
[[[0.76519932 0.42297653 0.85628587 0.35031202]
  [0.60195412 0.75413339 0.314559   0.0043912 ]
  [0.62228753 0.32976213 0.16372957 0.16570839]
  [0.94379182 0.49528202 0.93511062 0.37641666]
  [0.14683645 0.25504818 0.05685097 0.56226229]]

 [[0.22363455 0.97554161 0.75882726 0.87738934]
  [0.67386105 0.09225639 0.89201805 0.86386798]
  [0.10049627 0.07675318 0.54238259 0.14946104]
  [0.66276678 0.08827035 0.62139288 0.1258139 ]
  [0.78791224 0.83730186 0.46207662 0.87842228]]

 [[0.43734099 0.65583789 0.21051061 0.08527541]
  [0.04425003 0.28452149 0.20626041 0.23874844]
  [0.870

# Indexing

## 1D array indexing

In [33]:
arr=np.arange(10,101,10)
print(arr)
print(arr[2])
print(arr[-1])

[ 10  20  30  40  50  60  70  80  90 100]
30
100


## 2D array indexing

In [34]:
arr=np.random.randint(1,100,(4,5))
print(arr)
print(arr[1,1])
print(arr[1][1])

[[52 70 80  5 49]
 [15 67 58 14 54]
 [88 51 63 34 29]
 [49 43  8 71 60]]
67
67


## 3D array indexing

In [35]:
arr=np.random.randint(1,100,(3,2,4))
print(arr)
print('*'*100)
print(arr[0,1,3])
print('*'*100)
print(arr[0][1][3])

[[[55 85 77  3]
  [80 82 89 59]]

 [[55  9 94 23]
  [ 3 57 52 58]]

 [[25 45 62 96]
  [29 94 62 94]]]
****************************************************************************************************
59
****************************************************************************************************
59


# slicing

## 1d slicing

In [36]:
arr_1d=np.random.randint(1,100,10)
print(arr_1d)
print('*'*100)
print(arr_1d[2:5])
print('*'*100)
print(arr_1d[2:8:2])
print('*'*100)
print(arr_1d[2:])
print('*'*100)
print(arr_1d[:5])
print('*'*100)
print(arr_1d[::2])

[48 97 28 39 16 44 86 70  9 98]
****************************************************************************************************
[28 39 16]
****************************************************************************************************
[28 16 86]
****************************************************************************************************
[28 39 16 44 86 70  9 98]
****************************************************************************************************
[48 97 28 39 16]
****************************************************************************************************
[48 28 16 86  9]


## 2d slicing

In [37]:
arr_2d=np.random.randint(1,100,(4,6))
print(arr_2d)
print('*'*100)
print(arr_2d[1,2:4])
print('*'*100)
print(arr_2d[2:4,1:3])

[[54 57 78 72 69 41]
 [42 93 25 19 85 25]
 [42 52 75  1 74 50]
 [32 91 21 90 31 14]]
****************************************************************************************************
[25 19]
****************************************************************************************************
[[52 75]
 [91 21]]


## 3d slicing

In [38]:
arr_3d=np.random.randint(1,100,(4,4,5))
print(arr_3d)
print('*'*100)
print(arr_3d[2,0,1:])
print('*'*100)
print(arr_3d[1:3,1:3,1:3])

[[[78 93 47 94 64]
  [16 63 10 38 46]
  [51 41 40 53 40]
  [43 91  8 11 75]]

 [[22  2 60 36 69]
  [88 63  2 40 66]
  [81 55 46 49 46]
  [60 59 71 45 48]]

 [[ 9 55 73  8  3]
  [33 31 78 16 72]
  [57 31 73  6 83]
  [93 35 18 56 14]]

 [[98 97 82 87 68]
  [43 64 41 89 67]
  [ 6 25 31 42 45]
  [36 90 95 55 56]]]
****************************************************************************************************
[55 73  8  3]
****************************************************************************************************
[[[63  2]
  [55 46]]

 [[31 78]
  [31 73]]]


In [41]:
arr=np.random.randint(1,100,15)
sum=arr.sum()
print(arr)
print(sum)
print(arr.max())
print(arr.min())

[53  2 76  1 49 37 71 38  2 15  1 22 82 36 28]
513
82
1


## argmax

In [ ]:
arr.argmax()    # Return index of max value

np.int64(12)

## concat

In [49]:
arr1=np.random.randint(1,100,(2,2))
arr2=np.random.randint(1,100,(2,2))
print(arr1)
print(arr2)
arr3=np.concat([arr1,arr2],axis=0)
print(arr3)

[[ 2 81]
 [22 11]]
[[13 39]
 [63 75]]
[[ 2 81]
 [22 11]
 [13 39]
 [63 75]]


## sort

In [1080]:
arr=np.random.randint(1,100,15)
print(arr)
arr.sort()
print(arr)


[89 36 40 35  4 32 47 45 56 43 63  4  6 14 77]
[ 4  4  6 14 32 35 36 40 43 45 47 56 63 77 89]


## copy

In [1081]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [1082]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## view

In [1083]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [1084]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## find indices

In [1085]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [1086]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)
